[numpy]
infer = false
execute_exclude_patterns = ['numpy._', 'numpy.testing._priv', 'numpy.errstate', 'numpy.seterr', 'numpy.bincount',
'numpy.core._multiarray_umath.bincount', 'numpy.core._multiarray_umath.datetime_as_string',
'numpy.core._multiarray_umath.normalize_axis_index', 'numpy.core._multiarray_umath.shares_memory',
'numpy.datetime_as_string', 'numpy.shares_memory', 'numpy.squeeze',
'numpy.average',
'numpy.ctypeslib', 'numpy.append']
exec_failure = 'fallback'
source = 'https://github.com/numpy/numpy'
homepage = 'https://numpy.org'
docs = 'https://numpy.org/doc/stable/'
logo = 'numpy_logo.png'
[scipy]
logo = 'scipy_logo.png'

[matplotlib]
logo = 'matplotlib_logo.png'
wait_for_plt_show = false
submodules = [
 "image", 
 "pyplot",
 "axes",
 "axes._base",
 "dviread",
 "image"
]
[papyri]
logo = 'papyri-logo.png'

[IPython]
logo = 'ipython-logo.png'
exec_failure = 'fallback'


[dask]
logo = 'dask-logo.png'

[skimage]
logo = 'skimage-logo.png'



