[numpy]
infer = false
execute_exclude_patterns = ['numpy._', 'numpy.testing._priv', 'numpy.errstate', 'numpy.seterr', 'numpy.bincount',
'numpy.core._multiarray_umath.bincount', 'numpy.core._multiarray_umath.datetime_as_string',
'numpy.core._multiarray_umath.normalize_axis_index', 'numpy.core._multiarray_umath.shares_memory',
'numpy.datetime_as_string', 'numpy.shares_memory', 'numpy.squeeze',
'numpy.average',
'numpy.ctypeslib', 'numpy.append', 'numpy.ma.core']
exclude = ['numpy.testing._private.nosetester.NoseTester', 'numpy._pytesttester', 'numpy.all']
exec_failure = 'fallback'
source = 'https://github.com/numpy/numpy'
homepage = 'https://numpy.org'
docs = 'https://numpy.org/doc/stable/'
logo = 'numpy_logo.png'
[scipy]
logo = 'scipy_logo.png'
submodules = [
 "signal", 
]

exclude = ["scipy.signal.spectral._spectral_helper"]
exclude_jedi = ['scipy.linalg._sketches.clarkson_woodruff_transform','scipy.optimize._lsq.least_squares.least_squares']

execute_exclude_patterns = []
exec_failure = 'fallback'

[matplotlib]
logo = 'matplotlib_logo.png'
wait_for_plt_show = false
exec_failure = "fallback"
submodules = [
 "image", 
 "pyplot",
 "axes",
 "axes._base",
 "dviread",
 "image"
]


[papyri]
logo = 'papyri-logo.png'
examples_folder = '~/dev/papyri/examples/'

[IPython]
logo = 'ipython-logo.png'
exec_failure = 'fallback'


[dask]
logo = 'dask-logo.png'
exclude = ['dask.utils.Dispatch']

[skimage]
logo = 'skimage-logo.png'
exec_failure = "fallback"
submodules = [
 "morphology", 
 "color",
 "data",
 "draw",
 "exposure",
 "io",
 "graph",
 "segmentation",
 "transform",
 "util",
 "viewer"
]
[astropy]
submodules = [
 "io", 
 "io.fits"
]






